/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.Heroi;
import model.Jogador;
import model.Login;
import dao.JogadorDAO;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.UIManager;

/**
 *
 * @author Luiz
 */
public class TelaInformacoesGUI extends javax.swing.JFrame {

    private Jogador jogador;

    /**
     * Creates new form TelaInformacoesGUI
     */
    public TelaInformacoesGUI() {
        initComponents();

        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDadosJogador = new javax.swing.JPanel();
        textoApelido = new javax.swing.JLabel();
        painelHeroi = new javax.swing.JPanel();
        JLabel2 = new javax.swing.JLabel();
        terceiraEstrela = new javax.swing.JLabel();
        segundaEstrela = new javax.swing.JLabel();
        primeiroEstrela = new javax.swing.JLabel();
        textoHeroiSelecionado = new javax.swing.JLabel();
        painelInformacoesJogador = new javax.swing.JPanel();
        JLabel1 = new javax.swing.JLabel();
        textoPontuacao = new javax.swing.JLabel();
        painelCarteira = new javax.swing.JPanel();
        textoMoeda = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        painelMochila = new javax.swing.JPanel();
        textoAgua = new javax.swing.JLabel();
        textoGarrafa = new javax.swing.JLabel();
        textoVitamina = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botaoHerois = new javax.swing.JButton();
        textoUsuario = new javax.swing.JLabel();
        painelBotoes = new javax.swing.JPanel();
        botaoLoja = new javax.swing.JButton();
        botaoJogar = new javax.swing.JButton();
        botaoRank = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BROKEN WORDS BATTLE");
        setResizable(false);

        painelDadosJogador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil do jogador", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 12))); // NOI18N

        textoApelido.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoApelido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoApelido.setText("Apelido");
        textoApelido.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        painelHeroi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        JLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        JLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemHeroi.png"))); // NOI18N
        JLabel2.setText("Herói:");

        terceiraEstrela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemEstrelaVazia.png"))); // NOI18N

        segundaEstrela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemEstrelaVazia.png"))); // NOI18N

        primeiroEstrela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemEstrelaVazia.png"))); // NOI18N

        textoHeroiSelecionado.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoHeroiSelecionado.setText("Aprendiz");

        javax.swing.GroupLayout painelHeroiLayout = new javax.swing.GroupLayout(painelHeroi);
        painelHeroi.setLayout(painelHeroiLayout);
        painelHeroiLayout.setHorizontalGroup(
            painelHeroiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelHeroiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoHeroiSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(primeiroEstrela)
                .addGap(18, 18, 18)
                .addComponent(segundaEstrela)
                .addGap(18, 18, 18)
                .addComponent(terceiraEstrela)
                .addContainerGap())
        );
        painelHeroiLayout.setVerticalGroup(
            painelHeroiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(terceiraEstrela, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(segundaEstrela)
            .addComponent(primeiroEstrela)
            .addGroup(painelHeroiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(JLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(textoHeroiSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelInformacoesJogador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        JLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        JLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemPontuacao.png"))); // NOI18N
        JLabel1.setText("Pontuação:");

        textoPontuacao.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoPontuacao.setText("0");

        javax.swing.GroupLayout painelInformacoesJogadorLayout = new javax.swing.GroupLayout(painelInformacoesJogador);
        painelInformacoesJogador.setLayout(painelInformacoesJogadorLayout);
        painelInformacoesJogadorLayout.setHorizontalGroup(
            painelInformacoesJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformacoesJogadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelInformacoesJogadorLayout.setVerticalGroup(
            painelInformacoesJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInformacoesJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(textoPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelCarteira.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        textoMoeda.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoMoeda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemDinheiro.png"))); // NOI18N
        textoMoeda.setText("0");

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemCarteira.png"))); // NOI18N
        jLabel5.setText("Carteira:");

        javax.swing.GroupLayout painelCarteiraLayout = new javax.swing.GroupLayout(painelCarteira);
        painelCarteira.setLayout(painelCarteiraLayout);
        painelCarteiraLayout.setHorizontalGroup(
            painelCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCarteiraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelCarteiraLayout.setVerticalGroup(
            painelCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(textoMoeda)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelMochila.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        painelMochila.setPreferredSize(new java.awt.Dimension(0, 29));

        textoAgua.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemAguaMenor.png"))); // NOI18N
        textoAgua.setText("0");

        textoGarrafa.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoGarrafa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemGarrafaMenor.png"))); // NOI18N
        textoGarrafa.setText("0");

        textoVitamina.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoVitamina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemVitaminaMenor.png"))); // NOI18N
        textoVitamina.setText("0");

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemMochila.png"))); // NOI18N
        jLabel4.setText("Mochila:");

        javax.swing.GroupLayout painelMochilaLayout = new javax.swing.GroupLayout(painelMochila);
        painelMochila.setLayout(painelMochilaLayout);
        painelMochilaLayout.setHorizontalGroup(
            painelMochilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMochilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoAgua)
                .addGap(18, 18, 18)
                .addComponent(textoGarrafa)
                .addGap(18, 18, 18)
                .addComponent(textoVitamina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelMochilaLayout.setVerticalGroup(
            painelMochilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMochilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(textoAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoGarrafa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(textoVitamina, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        botaoHerois.setBackground(new java.awt.Color(153, 0, 255));
        botaoHerois.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        botaoHerois.setText("Heróis");
        botaoHerois.setFocusPainted(false);
        botaoHerois.setFocusable(false);
        botaoHerois.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoHerois.setPreferredSize(new java.awt.Dimension(57, 57));
        botaoHerois.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoHerois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHeroisActionPerformed(evt);
            }
        });

        textoUsuario.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoUsuario.setText("Usuario");
        textoUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout painelDadosJogadorLayout = new javax.swing.GroupLayout(painelDadosJogador);
        painelDadosJogador.setLayout(painelDadosJogadorLayout);
        painelDadosJogadorLayout.setHorizontalGroup(
            painelDadosJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosJogadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelInformacoesJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosJogadorLayout.createSequentialGroup()
                        .addComponent(botaoHerois, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoApelido, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(textoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(painelHeroi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelMochila, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(painelCarteira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelDadosJogadorLayout.setVerticalGroup(
            painelDadosJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosJogadorLayout.createSequentialGroup()
                .addGroup(painelDadosJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosJogadorLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(textoApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosJogadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelDadosJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoHerois, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelHeroi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelInformacoesJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelMochila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botaoLoja.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        botaoLoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemLoja.png"))); // NOI18N
        botaoLoja.setText("LOJA");
        botaoLoja.setFocusPainted(false);
        botaoLoja.setFocusable(false);
        botaoLoja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoLoja.setPreferredSize(new java.awt.Dimension(81, 75));
        botaoLoja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLojaActionPerformed(evt);
            }
        });

        botaoJogar.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        botaoJogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemJogar.png"))); // NOI18N
        botaoJogar.setText("JOGAR");
        botaoJogar.setFocusPainted(false);
        botaoJogar.setFocusable(false);
        botaoJogar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoJogar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogarActionPerformed(evt);
            }
        });

        botaoRank.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        botaoRank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemRank.png"))); // NOI18N
        botaoRank.setText("RANK");
        botaoRank.setFocusPainted(false);
        botaoRank.setFocusable(false);
        botaoRank.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoRank.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRankActionPerformed(evt);
            }
        });

        botaoSair.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemSair.png"))); // NOI18N
        botaoSair.setText("SAIR");
        botaoSair.setFocusPainted(false);
        botaoSair.setFocusable(false);
        botaoSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoJogar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoJogar)
                    .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoRank)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDadosJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDadosJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/iconeJogo.png")));
    }

    public void populaTela(Login login) {
        JogadorDAO jogadorDao = new JogadorDAO();

        jogador = jogadorDao.pesquisaJogador(login.getUsuario());

        Heroi heroi = new Heroi(jogador.getHeroiSelecionado());

        heroi.defineHeroi();

        String imagem = heroi.getImagemHeroi();
        Color color = heroi.getColor();

        botaoHerois.setIcon(new javax.swing.ImageIcon(getClass().getResource(imagem)));
        botaoHerois.setBackground(color);

        textoHeroiSelecionado.setText(jogador.getHeroiSelecionado());
        textoUsuario.setText(login.getUsuario());
        textoApelido.setText(login.getApelido());
        textoPontuacao.setText(Integer.toString(jogador.getPontuacao()));
        textoMoeda.setText(Integer.toString(jogador.getCarteira()));
        textoAgua.setText(Integer.toString(jogador.getAguaMineral()));
        textoGarrafa.setText(Integer.toString(jogador.getGarrafaCafe()));
        textoVitamina.setText(Integer.toString(jogador.getVitamina()));
    }

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        TelaPrincipalGUI telaPrincipal = new TelaPrincipalGUI();

        telaPrincipal.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLojaActionPerformed
        TelaLojaGUI telaLoja = new TelaLojaGUI();

        telaLoja.idJogador = jogador.getIdJogador();

        String usuario = textoUsuario.getText();
        telaLoja.textoUsuario.setText(usuario);

        String apelido = textoApelido.getText();
        telaLoja.textoApelido.setText(apelido);

        String moeda = textoMoeda.getText();
        telaLoja.textoMoeda.setText(moeda);

        String agua = textoAgua.getText();
        telaLoja.textoAgua.setText(agua);

        String garrafa = textoGarrafa.getText();
        telaLoja.textoGarrafa.setText(garrafa);

        String vitamina = textoVitamina.getText();
        telaLoja.textoVitamina.setText(vitamina);

        telaLoja.validarValores();
        telaLoja.validarHerois(jogador);

        telaLoja.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_botaoLojaActionPerformed

    private void botaoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoJogarActionPerformed
        TelaJogoGUI telaJogo = new TelaJogoGUI();

        telaJogo.botaoHabilidadeHeroi.setBackground(botaoHerois.getBackground());
        telaJogo.botaoHabilidadeHeroi.setIcon(botaoHerois.getIcon());
        telaJogo.textoJogador.setText(textoApelido.getText());

        int qtdAgua = Integer.parseInt(textoAgua.getText());
        int qtdGarrafa = Integer.parseInt(textoGarrafa.getText());
        int qtdVitamina = Integer.parseInt(textoVitamina.getText());

        if (qtdAgua > 0) {
            telaJogo.botaoAgua.setEnabled(true);
        } else {
            telaJogo.botaoAgua.setEnabled(false);
        }

        if (qtdGarrafa > 0) {
            telaJogo.botaoGarrafa.setEnabled(true);
        } else {
            telaJogo.botaoGarrafa.setEnabled(false);
        }

        if (qtdVitamina > 0) {
            telaJogo.botaoVitamina.setEnabled(true);
        } else {
            telaJogo.botaoVitamina.setEnabled(false);
        }

        telaJogo.usuario = textoUsuario.getText();
        telaJogo.apelido = textoApelido.getText();
        telaJogo.idJogador = jogador.getIdJogador();

        if (textoApelido.getText().equals("Convidado")) {
            telaJogo.heroiSelecionado = "APRENDIZ";
        } else {
            telaJogo.heroiSelecionado = jogador.getHeroiSelecionado();
        }

        telaJogo.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_botaoJogarActionPerformed

    private void botaoHeroisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHeroisActionPerformed
        TelaSelecaoHeroisGUI telaSelecaoHerois = new TelaSelecaoHeroisGUI();

        telaSelecaoHerois.usuario = textoUsuario.getText();
        telaSelecaoHerois.apelido = textoApelido.getText();
        telaSelecaoHerois.idJogador = jogador.getIdJogador();

        if (jogador.getCiborg() == 1) {
            telaSelecaoHerois.botaoCiborg.setEnabled(true);
        } else {
            telaSelecaoHerois.botaoCiborg.setEnabled(false);
        }

        if (jogador.getAndroid() == 1) {
            telaSelecaoHerois.botaoAndroid.setEnabled(true);
        } else {
            telaSelecaoHerois.botaoAndroid.setEnabled(false);
        }

        if (jogador.getPyro() == 1) {
            telaSelecaoHerois.botaoPyro.setEnabled(true);
        } else {
            telaSelecaoHerois.botaoPyro.setEnabled(false);
        }

        if (jogador.getViking() == 1) {
            telaSelecaoHerois.botaoViking.setEnabled(true);
        } else {
            telaSelecaoHerois.botaoViking.setEnabled(false);
        }

        telaSelecaoHerois.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_botaoHeroisActionPerformed

    private void botaoRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRankActionPerformed
        TelaRankGUI telaRank = new TelaRankGUI();

        telaRank.apelido = textoApelido.getText();
        telaRank.usuario = textoUsuario.getText();
        
        telaRank.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_botaoRankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInformacoesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInformacoesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInformacoesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInformacoesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInformacoesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel JLabel2;
    public javax.swing.JButton botaoHerois;
    private javax.swing.JButton botaoJogar;
    public javax.swing.JButton botaoLoja;
    public javax.swing.JButton botaoRank;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelCarteira;
    private javax.swing.JPanel painelDadosJogador;
    private javax.swing.JPanel painelHeroi;
    private javax.swing.JPanel painelInformacoesJogador;
    private javax.swing.JPanel painelMochila;
    private javax.swing.JLabel primeiroEstrela;
    private javax.swing.JLabel segundaEstrela;
    private javax.swing.JLabel terceiraEstrela;
    private javax.swing.JLabel textoAgua;
    public javax.swing.JLabel textoApelido;
    private javax.swing.JLabel textoGarrafa;
    private javax.swing.JLabel textoHeroiSelecionado;
    private javax.swing.JLabel textoMoeda;
    private javax.swing.JLabel textoPontuacao;
    public javax.swing.JLabel textoUsuario;
    private javax.swing.JLabel textoVitamina;
    // End of variables declaration//GEN-END:variables
}
