/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.Jogador;
import model.Login;
import dao.JogadorDAO;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Luiz
 */
public class TelaLojaGUI extends javax.swing.JFrame {

    public int idJogador;

    /**
     * Creates new form TelaLojaGUI
     */
    public TelaLojaGUI() {
        initComponents();
        
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelLoja = new javax.swing.JPanel();
        textoApelido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        painelMochila = new javax.swing.JPanel();
        textoAgua = new javax.swing.JLabel();
        textoGarrafa = new javax.swing.JLabel();
        textoVitamina = new javax.swing.JLabel();
        textoMoeda = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JLabel();
        painelPrincipal = new javax.swing.JTabbedPane();
        painelItens = new javax.swing.JScrollPane();
        painelDisposicaoItens = new javax.swing.JPanel();
        painelAguaMineral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        textoTotalAgua = new javax.swing.JLabel();
        botaoComprarAgua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        campoQtdAgua = new javax.swing.JTextField();
        botaoAddQtdAgua = new javax.swing.JButton();
        botaoRemQtdAgua = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        painelGarrafaCafe = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        textoTotalGarrafa = new javax.swing.JLabel();
        botaoComprarGarrafa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        campoQtdGarrafa = new javax.swing.JTextField();
        botaoAddQtdGarrafa = new javax.swing.JButton();
        botaoRemQtdGarrafa = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        painelVitamina = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        textoTotalVitamina = new javax.swing.JLabel();
        botaoComprarVitamina = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        campoQtdVitamina = new javax.swing.JTextField();
        botaoAddQtdVitamina = new javax.swing.JButton();
        botaoRemQtdVitamina = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        painelPersonagens = new javax.swing.JScrollPane();
        painelDisposicaoPersonagen = new javax.swing.JPanel();
        painelCiborg = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        textoValorCiborg = new javax.swing.JLabel();
        botaoComprarCiborg = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        painelAndroid = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        textoValorAndroid = new javax.swing.JLabel();
        botaoComprarAndroid = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        painelPyro = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        textoValorPyro = new javax.swing.JLabel();
        botaoComprarPyro = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        painelViking = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        textoValorViking = new javax.swing.JLabel();
        botaoComprarViking = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BROKEN WORDS BATTLE");
        setResizable(false);

        painelLoja.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loja de itens e personagens", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 12))); // NOI18N

        textoApelido.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoApelido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoApelido.setText("Apelido");
        textoApelido.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemCarteira.png"))); // NOI18N
        jLabel5.setText("Saldo:");

        botaoSair.setBackground(new java.awt.Color(0, 204, 0));
        botaoSair.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemSair.png"))); // NOI18N
        botaoSair.setText("VOLTAR");
        botaoSair.setFocusPainted(false);
        botaoSair.setFocusable(false);
        botaoSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemMochila.png"))); // NOI18N
        jLabel11.setText("Mochila:");

        painelMochila.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        painelMochila.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelMochila.setFocusable(false);
        painelMochila.setPreferredSize(new java.awt.Dimension(0, 29));

        textoAgua.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemAguaMenor.png"))); // NOI18N
        textoAgua.setText("0");

        textoGarrafa.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoGarrafa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemGarrafaMenor.png"))); // NOI18N
        textoGarrafa.setText("0");

        textoVitamina.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoVitamina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemVitaminaMenor.png"))); // NOI18N
        textoVitamina.setText("0");

        javax.swing.GroupLayout painelMochilaLayout = new javax.swing.GroupLayout(painelMochila);
        painelMochila.setLayout(painelMochilaLayout);
        painelMochilaLayout.setHorizontalGroup(
            painelMochilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMochilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoAgua)
                .addGap(18, 18, 18)
                .addComponent(textoGarrafa)
                .addGap(16, 16, 16)
                .addComponent(textoVitamina, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelMochilaLayout.setVerticalGroup(
            painelMochilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMochilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(textoAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoGarrafa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(textoVitamina, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        textoMoeda.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoMoeda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoMoeda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemDinheiro.png"))); // NOI18N
        textoMoeda.setText("0");
        textoMoeda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        textoUsuario.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoUsuario.setText("Usuario");
        textoUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout painelLojaLayout = new javax.swing.GroupLayout(painelLoja);
        painelLoja.setLayout(painelLojaLayout);
        painelLojaLayout.setHorizontalGroup(
            painelLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLojaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoApelido, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(textoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLojaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoMoeda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelLojaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelMochila, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelLojaLayout.setVerticalGroup(
            painelLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLojaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelLojaLayout.createSequentialGroup()
                        .addGroup(painelLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(painelMochila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoMoeda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoApelido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelPrincipal.setFocusable(false);
        painelPrincipal.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        painelPrincipal.setRequestFocusEnabled(false);

        painelAguaMineral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Água Mineral", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 12))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemAgua.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        jScrollPane1.setToolTipText("");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setText("Água Mineral cura 5 pontos da vida do herói.\nObs.: Só pode ser usada uma vez.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        textoTotalAgua.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoTotalAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTotalAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemDinheiro.png"))); // NOI18N
        textoTotalAgua.setText("1000");
        textoTotalAgua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botaoComprarAgua.setBackground(new java.awt.Color(153, 153, 0));
        botaoComprarAgua.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        botaoComprarAgua.setText("COMPRAR");
        botaoComprarAgua.setFocusPainted(false);
        botaoComprarAgua.setFocusable(false);
        botaoComprarAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComprarAguaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel6.setText("Qtd:");

        campoQtdAgua.setEditable(false);
        campoQtdAgua.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        campoQtdAgua.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoQtdAgua.setText("1");

        botaoAddQtdAgua.setBackground(new java.awt.Color(0, 0, 255));
        botaoAddQtdAgua.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        botaoAddQtdAgua.setText("+");
        botaoAddQtdAgua.setFocusPainted(false);
        botaoAddQtdAgua.setFocusable(false);
        botaoAddQtdAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddQtdAguaActionPerformed(evt);
            }
        });

        botaoRemQtdAgua.setBackground(new java.awt.Color(255, 0, 0));
        botaoRemQtdAgua.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        botaoRemQtdAgua.setText("-");
        botaoRemQtdAgua.setFocusPainted(false);
        botaoRemQtdAgua.setFocusable(false);
        botaoRemQtdAgua.setPreferredSize(new java.awt.Dimension(41, 23));
        botaoRemQtdAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemQtdAguaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel9.setText("Moedas");

        javax.swing.GroupLayout painelAguaMineralLayout = new javax.swing.GroupLayout(painelAguaMineral);
        painelAguaMineral.setLayout(painelAguaMineralLayout);
        painelAguaMineralLayout.setHorizontalGroup(
            painelAguaMineralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAguaMineralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAguaMineralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(botaoComprarAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelAguaMineralLayout.createSequentialGroup()
                        .addComponent(textoTotalAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQtdAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAddQtdAgua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRemQtdAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelAguaMineralLayout.setVerticalGroup(
            painelAguaMineralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAguaMineralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAguaMineralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelAguaMineralLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelAguaMineralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoQtdAgua)
                            .addComponent(botaoAddQtdAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoRemQtdAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(painelAguaMineralLayout.createSequentialGroup()
                                .addGroup(painelAguaMineralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelAguaMineralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(textoTotalAgua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoComprarAgua))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelGarrafaCafe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Garrafa de Café", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 12))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemGarrafa.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jScrollPane2.setToolTipText("");

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(2);
        jTextArea2.setText("Garrafa de Café cura toda a vida do herói.\nObs.: Só pode ser usada uma vez.");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        textoTotalGarrafa.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoTotalGarrafa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTotalGarrafa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemDinheiro.png"))); // NOI18N
        textoTotalGarrafa.setText("5000");
        textoTotalGarrafa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botaoComprarGarrafa.setBackground(new java.awt.Color(153, 153, 0));
        botaoComprarGarrafa.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        botaoComprarGarrafa.setText("COMPRAR");
        botaoComprarGarrafa.setFocusPainted(false);
        botaoComprarGarrafa.setFocusable(false);
        botaoComprarGarrafa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComprarGarrafaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel8.setText("Qtd:");

        campoQtdGarrafa.setEditable(false);
        campoQtdGarrafa.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        campoQtdGarrafa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoQtdGarrafa.setText("1");

        botaoAddQtdGarrafa.setBackground(new java.awt.Color(0, 0, 255));
        botaoAddQtdGarrafa.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        botaoAddQtdGarrafa.setText("+");
        botaoAddQtdGarrafa.setFocusPainted(false);
        botaoAddQtdGarrafa.setFocusable(false);
        botaoAddQtdGarrafa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddQtdGarrafaActionPerformed(evt);
            }
        });

        botaoRemQtdGarrafa.setBackground(new java.awt.Color(255, 0, 0));
        botaoRemQtdGarrafa.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        botaoRemQtdGarrafa.setText("-");
        botaoRemQtdGarrafa.setFocusPainted(false);
        botaoRemQtdGarrafa.setFocusable(false);
        botaoRemQtdGarrafa.setPreferredSize(new java.awt.Dimension(41, 23));
        botaoRemQtdGarrafa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemQtdGarrafaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel7.setText("Moedas");

        javax.swing.GroupLayout painelGarrafaCafeLayout = new javax.swing.GroupLayout(painelGarrafaCafe);
        painelGarrafaCafe.setLayout(painelGarrafaCafeLayout);
        painelGarrafaCafeLayout.setHorizontalGroup(
            painelGarrafaCafeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGarrafaCafeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelGarrafaCafeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(botaoComprarGarrafa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelGarrafaCafeLayout.createSequentialGroup()
                        .addComponent(textoTotalGarrafa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQtdGarrafa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAddQtdGarrafa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRemQtdGarrafa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelGarrafaCafeLayout.setVerticalGroup(
            painelGarrafaCafeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGarrafaCafeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelGarrafaCafeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelGarrafaCafeLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(painelGarrafaCafeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelGarrafaCafeLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(painelGarrafaCafeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoRemQtdGarrafa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(painelGarrafaCafeLayout.createSequentialGroup()
                                        .addComponent(textoTotalGarrafa)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(painelGarrafaCafeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoAddQtdGarrafa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(painelGarrafaCafeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoQtdGarrafa))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGarrafaCafeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(painelGarrafaCafeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoComprarGarrafa))
                    .addComponent(jLabel2)))
        );

        painelVitamina.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vitamina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 12))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemVitamina.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jScrollPane3.setToolTipText("");

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(3);
        jTextArea3.setText("Vitamina dobra a quantidade de pontos ganhos em toda rodada.\nObs.: Só pode ser usada uma vez.");
        jTextArea3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea3);

        textoTotalVitamina.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoTotalVitamina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTotalVitamina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemDinheiro.png"))); // NOI18N
        textoTotalVitamina.setText("15000");
        textoTotalVitamina.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botaoComprarVitamina.setBackground(new java.awt.Color(153, 153, 0));
        botaoComprarVitamina.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        botaoComprarVitamina.setText("COMPRAR");
        botaoComprarVitamina.setFocusPainted(false);
        botaoComprarVitamina.setFocusable(false);
        botaoComprarVitamina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComprarVitaminaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel10.setText("Qtd:");

        campoQtdVitamina.setEditable(false);
        campoQtdVitamina.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        campoQtdVitamina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoQtdVitamina.setText("1");

        botaoAddQtdVitamina.setBackground(new java.awt.Color(0, 0, 255));
        botaoAddQtdVitamina.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        botaoAddQtdVitamina.setText("+");
        botaoAddQtdVitamina.setFocusPainted(false);
        botaoAddQtdVitamina.setFocusable(false);
        botaoAddQtdVitamina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddQtdVitaminaActionPerformed(evt);
            }
        });

        botaoRemQtdVitamina.setBackground(new java.awt.Color(255, 0, 0));
        botaoRemQtdVitamina.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        botaoRemQtdVitamina.setText("-");
        botaoRemQtdVitamina.setFocusPainted(false);
        botaoRemQtdVitamina.setFocusable(false);
        botaoRemQtdVitamina.setPreferredSize(new java.awt.Dimension(41, 23));
        botaoRemQtdVitamina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemQtdVitaminaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel4.setText("Moedas");

        javax.swing.GroupLayout painelVitaminaLayout = new javax.swing.GroupLayout(painelVitamina);
        painelVitamina.setLayout(painelVitaminaLayout);
        painelVitaminaLayout.setHorizontalGroup(
            painelVitaminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVitaminaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelVitaminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(botaoComprarVitamina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelVitaminaLayout.createSequentialGroup()
                        .addComponent(textoTotalVitamina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQtdVitamina, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAddQtdVitamina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRemQtdVitamina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelVitaminaLayout.setVerticalGroup(
            painelVitaminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVitaminaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelVitaminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelVitaminaLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(painelVitaminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoAddQtdVitamina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoQtdVitamina, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoRemQtdVitamina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelVitaminaLayout.createSequentialGroup()
                                .addComponent(textoTotalVitamina)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoComprarVitamina))))
        );

        javax.swing.GroupLayout painelDisposicaoItensLayout = new javax.swing.GroupLayout(painelDisposicaoItens);
        painelDisposicaoItens.setLayout(painelDisposicaoItensLayout);
        painelDisposicaoItensLayout.setHorizontalGroup(
            painelDisposicaoItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDisposicaoItensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDisposicaoItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelAguaMineral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelGarrafaCafe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelVitamina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelDisposicaoItensLayout.setVerticalGroup(
            painelDisposicaoItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDisposicaoItensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelAguaMineral, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelGarrafaCafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelVitamina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelItens.setViewportView(painelDisposicaoItens);

        painelPrincipal.addTab("Itens", painelItens);

        painelCiborg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ciborg", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 12))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemCiborg.png"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane7.setToolTipText("");

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        jTextArea7.setLineWrap(true);
        jTextArea7.setRows(2);
        jTextArea7.setText("Descrição: Seu visor interfere os eletrônicos!!\nHabilidade: Dobra a pontuação atual.");
        jTextArea7.setWrapStyleWord(true);
        jScrollPane7.setViewportView(jTextArea7);

        textoValorCiborg.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoValorCiborg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoValorCiborg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemDinheiro.png"))); // NOI18N
        textoValorCiborg.setText("100000");
        textoValorCiborg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botaoComprarCiborg.setBackground(new java.awt.Color(0, 0, 0));
        botaoComprarCiborg.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        botaoComprarCiborg.setText("COMPRAR");
        botaoComprarCiborg.setFocusPainted(false);
        botaoComprarCiborg.setFocusable(false);
        botaoComprarCiborg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComprarCiborgActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel21.setText("Moedas");

        javax.swing.GroupLayout painelCiborgLayout = new javax.swing.GroupLayout(painelCiborg);
        painelCiborg.setLayout(painelCiborgLayout);
        painelCiborgLayout.setHorizontalGroup(
            painelCiborgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCiborgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCiborgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addComponent(botaoComprarCiborg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelCiborgLayout.createSequentialGroup()
                        .addComponent(textoValorCiborg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(175, 175, 175)))
                .addContainerGap())
        );
        painelCiborgLayout.setVerticalGroup(
            painelCiborgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCiborgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCiborgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelCiborgLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelCiborgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textoValorCiborg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoComprarCiborg))
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelAndroid.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Android", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 12))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemAndroid.png"))); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        jScrollPane6.setToolTipText("");

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(2);
        jTextArea6.setText("Descrição: Ajuda os necessitados!!\nHabilidade: Cura toda a vida do jogador.");
        jTextArea6.setWrapStyleWord(true);
        jScrollPane6.setViewportView(jTextArea6);

        textoValorAndroid.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoValorAndroid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoValorAndroid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemDinheiro.png"))); // NOI18N
        textoValorAndroid.setText("100000");
        textoValorAndroid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botaoComprarAndroid.setBackground(new java.awt.Color(153, 153, 255));
        botaoComprarAndroid.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        botaoComprarAndroid.setText("COMPRAR");
        botaoComprarAndroid.setFocusPainted(false);
        botaoComprarAndroid.setFocusable(false);
        botaoComprarAndroid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComprarAndroidActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel20.setText("Moedas");

        javax.swing.GroupLayout painelAndroidLayout = new javax.swing.GroupLayout(painelAndroid);
        painelAndroid.setLayout(painelAndroidLayout);
        painelAndroidLayout.setHorizontalGroup(
            painelAndroidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAndroidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAndroidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addComponent(botaoComprarAndroid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelAndroidLayout.createSequentialGroup()
                        .addComponent(textoValorAndroid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addGap(175, 175, 175)))
                .addContainerGap())
        );
        painelAndroidLayout.setVerticalGroup(
            painelAndroidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAndroidLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAndroidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelAndroidLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelAndroidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textoValorAndroid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoComprarAndroid))
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelPyro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pyro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 12))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemPyro.png"))); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jScrollPane8.setToolTipText("");

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        jTextArea8.setLineWrap(true);
        jTextArea8.setRows(2);
        jTextArea8.setText("Descrição: Cuidado para não queimar!!\nHabilidade: Pule o nível e ganhe pontuação bônus.");
        jTextArea8.setWrapStyleWord(true);
        jScrollPane8.setViewportView(jTextArea8);

        textoValorPyro.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoValorPyro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoValorPyro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemDinheiro.png"))); // NOI18N
        textoValorPyro.setText("100000");
        textoValorPyro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botaoComprarPyro.setBackground(new java.awt.Color(204, 0, 0));
        botaoComprarPyro.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        botaoComprarPyro.setText("COMPRAR");
        botaoComprarPyro.setFocusPainted(false);
        botaoComprarPyro.setFocusable(false);
        botaoComprarPyro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComprarPyroActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel23.setText("Moedas");

        javax.swing.GroupLayout painelPyroLayout = new javax.swing.GroupLayout(painelPyro);
        painelPyro.setLayout(painelPyroLayout);
        painelPyroLayout.setHorizontalGroup(
            painelPyroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPyroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPyroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addComponent(botaoComprarPyro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelPyroLayout.createSequentialGroup()
                        .addComponent(textoValorPyro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addGap(175, 175, 175)))
                .addContainerGap())
        );
        painelPyroLayout.setVerticalGroup(
            painelPyroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPyroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPyroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelPyroLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelPyroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textoValorPyro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoComprarPyro))
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelViking.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Viking", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 12))); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemViking.png"))); // NOI18N
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        jScrollPane10.setToolTipText("");

        jTextArea10.setEditable(false);
        jTextArea10.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        jTextArea10.setLineWrap(true);
        jTextArea10.setRows(2);
        jTextArea10.setText("Descrição: Consegue manipular o tempo!!\nHabilidade: Dobra o tempo de jogo atual.");
        jTextArea10.setWrapStyleWord(true);
        jScrollPane10.setViewportView(jTextArea10);

        textoValorViking.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoValorViking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoValorViking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemDinheiro.png"))); // NOI18N
        textoValorViking.setText("100000");
        textoValorViking.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botaoComprarViking.setBackground(new java.awt.Color(0, 153, 51));
        botaoComprarViking.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        botaoComprarViking.setText("COMPRAR");
        botaoComprarViking.setFocusPainted(false);
        botaoComprarViking.setFocusable(false);
        botaoComprarViking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComprarVikingActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel27.setText("Moedas");

        javax.swing.GroupLayout painelVikingLayout = new javax.swing.GroupLayout(painelViking);
        painelViking.setLayout(painelVikingLayout);
        painelVikingLayout.setHorizontalGroup(
            painelVikingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVikingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelVikingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10)
                    .addComponent(botaoComprarViking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelVikingLayout.createSequentialGroup()
                        .addComponent(textoValorViking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addGap(175, 175, 175)))
                .addContainerGap())
        );
        painelVikingLayout.setVerticalGroup(
            painelVikingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVikingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelVikingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelVikingLayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelVikingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textoValorViking, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoComprarViking))
                    .addComponent(jLabel26))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelDisposicaoPersonagenLayout = new javax.swing.GroupLayout(painelDisposicaoPersonagen);
        painelDisposicaoPersonagen.setLayout(painelDisposicaoPersonagenLayout);
        painelDisposicaoPersonagenLayout.setHorizontalGroup(
            painelDisposicaoPersonagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDisposicaoPersonagenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDisposicaoPersonagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelCiborg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelAndroid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelPyro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelViking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelDisposicaoPersonagenLayout.setVerticalGroup(
            painelDisposicaoPersonagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDisposicaoPersonagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCiborg, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelAndroid, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPyro, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelViking, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelPersonagens.setViewportView(painelDisposicaoPersonagen);

        painelPrincipal.addTab("Personagens", painelPersonagens);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelPrincipal)
                    .addComponent(painelLoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/iconeJogo.png")));
    }

    public void validarValores() {
        int moedaAtual = Integer.parseInt(textoMoeda.getText());

        int valorAgua = Integer.parseInt(textoTotalAgua.getText());
        int valorGarrafa = Integer.parseInt(textoTotalGarrafa.getText());
        int valorVitamina = Integer.parseInt(textoTotalVitamina.getText());

        int valorCiborg = Integer.parseInt(textoValorCiborg.getText());
        int valorAndroid = Integer.parseInt(textoValorAndroid.getText());
        int valorPyro = Integer.parseInt(textoValorPyro.getText());
        int valorViking = Integer.parseInt(textoValorViking.getText());

        if (moedaAtual < valorAgua) {
            botaoComprarAgua.setEnabled(false);
        } else {
            botaoComprarAgua.setEnabled(true);
        }

        if (moedaAtual < valorGarrafa) {
            botaoComprarGarrafa.setEnabled(false);
        } else {
            botaoComprarGarrafa.setEnabled(true);
        }

        if (moedaAtual < valorVitamina) {
            botaoComprarVitamina.setEnabled(false);
        } else {
            botaoComprarVitamina.setEnabled(true);
        }

        if (moedaAtual < valorCiborg) {
            botaoComprarCiborg.setEnabled(false);
        } else {
            botaoComprarCiborg.setEnabled(true);
        }

        if (moedaAtual < valorAndroid) {
            botaoComprarAndroid.setEnabled(false);
        } else {
            botaoComprarAndroid.setEnabled(true);
        }

        if (moedaAtual < valorPyro) {
            botaoComprarPyro.setEnabled(false);
        } else {
            botaoComprarPyro.setEnabled(true);
        }

        if (moedaAtual < valorViking) {
            botaoComprarViking.setEnabled(false);
        } else {
            botaoComprarViking.setEnabled(true);
        }
    }

    public void validarHerois(Jogador jogador) {
        int moedaAtual = Integer.parseInt(textoMoeda.getText());

        int valorCiborg = Integer.parseInt(textoValorCiborg.getText());
        int valorAndroid = Integer.parseInt(textoValorAndroid.getText());
        int valorPyro = Integer.parseInt(textoValorPyro.getText());
        int valorViking = Integer.parseInt(textoValorViking.getText());

        if (moedaAtual > valorCiborg && jogador.getCiborg() == 1) {
            botaoComprarCiborg.setEnabled(false);
        }

        if (moedaAtual > valorAndroid && jogador.getAndroid() == 1) {
            botaoComprarAndroid.setEnabled(false);
        }

        if (moedaAtual > valorPyro && jogador.getPyro() == 1) {
            botaoComprarPyro.setEnabled(false);
        }

        if (moedaAtual > valorViking && jogador.getViking() == 1) {
            botaoComprarViking.setEnabled(false);
        }
    }

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        TelaInformacoesGUI telaInformacoes = new TelaInformacoesGUI();

        String apelido = textoApelido.getText();
        String usuario = textoUsuario.getText();

        Login login = new Login(apelido, usuario, "");

        telaInformacoes.populaTela(login);

        telaInformacoes.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoAddQtdAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddQtdAguaActionPerformed
        int numeroAtual = Integer.parseInt(campoQtdAgua.getText());

        if (numeroAtual < 100) {
            int valorAtual = Integer.parseInt(textoTotalAgua.getText());

            numeroAtual += 1;
            valorAtual += 1000;

            campoQtdAgua.setText(Integer.toString(numeroAtual));
            textoTotalAgua.setText(Integer.toString(valorAtual));
        }
    }//GEN-LAST:event_botaoAddQtdAguaActionPerformed

    private void botaoRemQtdAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemQtdAguaActionPerformed
        int numeroAtual = Integer.parseInt(campoQtdAgua.getText());

        if (numeroAtual > 1) {
            int valorAtual = Integer.parseInt(textoTotalAgua.getText());

            numeroAtual -= 1;
            valorAtual -= 1000;

            campoQtdAgua.setText(Integer.toString(numeroAtual));
            textoTotalAgua.setText(Integer.toString(valorAtual));
        }
    }//GEN-LAST:event_botaoRemQtdAguaActionPerformed

    private void botaoAddQtdGarrafaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddQtdGarrafaActionPerformed
        int numeroAtual = Integer.parseInt(campoQtdGarrafa.getText());

        if (numeroAtual < 100) {
            int valorAtual = Integer.parseInt(textoTotalGarrafa.getText());

            numeroAtual += 1;
            valorAtual += 5000;

            campoQtdGarrafa.setText(Integer.toString(numeroAtual));
            textoTotalGarrafa.setText(Integer.toString(valorAtual));
        }
    }//GEN-LAST:event_botaoAddQtdGarrafaActionPerformed

    private void botaoRemQtdGarrafaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemQtdGarrafaActionPerformed
        int numeroAtual = Integer.parseInt(campoQtdGarrafa.getText());

        if (numeroAtual > 1) {
            int valorAtual = Integer.parseInt(textoTotalGarrafa.getText());

            numeroAtual -= 1;
            valorAtual -= 5000;

            campoQtdGarrafa.setText(Integer.toString(numeroAtual));
            textoTotalGarrafa.setText(Integer.toString(valorAtual));
        }
    }//GEN-LAST:event_botaoRemQtdGarrafaActionPerformed

    private void botaoAddQtdVitaminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddQtdVitaminaActionPerformed
        int numeroAtual = Integer.parseInt(campoQtdVitamina.getText());

        if (numeroAtual < 100) {
            int valorAtual = Integer.parseInt(textoTotalVitamina.getText());

            numeroAtual += 1;
            valorAtual += 15000;

            campoQtdVitamina.setText(Integer.toString(numeroAtual));
            textoTotalVitamina.setText(Integer.toString(valorAtual));
        }
    }//GEN-LAST:event_botaoAddQtdVitaminaActionPerformed

    private void botaoRemQtdVitaminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemQtdVitaminaActionPerformed
        int numeroAtual = Integer.parseInt(campoQtdVitamina.getText());

        if (numeroAtual > 1) {
            int valorAtual = Integer.parseInt(textoTotalVitamina.getText());

            numeroAtual -= 1;
            valorAtual -= 15000;

            campoQtdVitamina.setText(Integer.toString(numeroAtual));
            textoTotalVitamina.setText(Integer.toString(valorAtual));
        }
    }//GEN-LAST:event_botaoRemQtdVitaminaActionPerformed

    private void botaoComprarAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComprarAguaActionPerformed
        int quantidade = Integer.parseInt(campoQtdAgua.getText());
        int carteira = Integer.parseInt(textoMoeda.getText());
        int valorItem = Integer.parseInt(textoTotalAgua.getText());

        JogadorDAO jogadorDao = new JogadorDAO();

        jogadorDao.atualizaAgua(quantidade, idJogador);
        jogadorDao.atualizaCarteira(valorItem, idJogador);

        int numeroAtual = Integer.parseInt(textoAgua.getText());

        textoAgua.setText(Integer.toString(quantidade + numeroAtual));
        textoMoeda.setText(Integer.toString(carteira - valorItem));

        JOptionPane.showMessageDialog(rootPane, quantidade + " unidade(s) de Agua Mineral comprado(s)");

        validarValores();
    }//GEN-LAST:event_botaoComprarAguaActionPerformed

    private void botaoComprarGarrafaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComprarGarrafaActionPerformed
        int quantidade = Integer.parseInt(campoQtdGarrafa.getText());
        int carteira = Integer.parseInt(textoMoeda.getText());
        int valorItem = Integer.parseInt(textoTotalGarrafa.getText());

        JogadorDAO jogadorDao = new JogadorDAO();

        jogadorDao.atualizaGarrafa(quantidade, idJogador);
        jogadorDao.atualizaCarteira(valorItem, idJogador);

        int numeroAtual = Integer.parseInt(textoGarrafa.getText());

        textoGarrafa.setText(Integer.toString(quantidade + numeroAtual));
        textoMoeda.setText(Integer.toString(carteira - valorItem));

        JOptionPane.showMessageDialog(rootPane, quantidade + " unidade(s) de Garrafa de Cafe comprado(s)");

        validarValores();
    }//GEN-LAST:event_botaoComprarGarrafaActionPerformed

    private void botaoComprarVitaminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComprarVitaminaActionPerformed
        int quantidade = Integer.parseInt(campoQtdVitamina.getText());
        int carteira = Integer.parseInt(textoMoeda.getText());
        int valorItem = Integer.parseInt(textoTotalVitamina.getText());

        JogadorDAO jogadorDao = new JogadorDAO();

        jogadorDao.atualizaVitamina(quantidade, idJogador);
        jogadorDao.atualizaCarteira(valorItem, idJogador);

        int numeroAtual = Integer.parseInt(textoVitamina.getText());

        textoVitamina.setText(Integer.toString(quantidade + numeroAtual));
        textoMoeda.setText(Integer.toString(carteira - valorItem));

        JOptionPane.showMessageDialog(rootPane, quantidade + " unidade(s) de Vitamina comprado(s)");

        validarValores();
    }//GEN-LAST:event_botaoComprarVitaminaActionPerformed

    private void botaoComprarCiborgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComprarCiborgActionPerformed
        int carteira = Integer.parseInt(textoMoeda.getText());
        int valorHeroi = Integer.parseInt(textoValorCiborg.getText());

        JogadorDAO jogadorDao = new JogadorDAO();

        jogadorDao.atualizaCiborg(idJogador);
        jogadorDao.atualizaCarteira(valorHeroi, idJogador);

        textoMoeda.setText(Integer.toString(carteira - valorHeroi));

        JOptionPane.showMessageDialog(rootPane, "Heroi CIBORG desbloqueado!!");

        validarValores();

        Jogador jogador = jogadorDao.pesquisaJogador(textoUsuario.getText());

        validarHerois(jogador);

        botaoComprarCiborg.setEnabled(false);
    }//GEN-LAST:event_botaoComprarCiborgActionPerformed

    private void botaoComprarAndroidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComprarAndroidActionPerformed
        int carteira = Integer.parseInt(textoMoeda.getText());
        int valorHeroi = Integer.parseInt(textoValorAndroid.getText());

        JogadorDAO jogadorDao = new JogadorDAO();

        jogadorDao.atualizaAndroid(idJogador);
        jogadorDao.atualizaCarteira(valorHeroi, idJogador);

        textoMoeda.setText(Integer.toString(carteira - valorHeroi));

        JOptionPane.showMessageDialog(rootPane, "Heroi ANDROID desbloqueado!!");

        validarValores();

        Jogador jogador = jogadorDao.pesquisaJogador(textoUsuario.getText());

        validarHerois(jogador);

        botaoComprarAndroid.setEnabled(false);
    }//GEN-LAST:event_botaoComprarAndroidActionPerformed

    private void botaoComprarPyroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComprarPyroActionPerformed
        int carteira = Integer.parseInt(textoMoeda.getText());
        int valorHeroi = Integer.parseInt(textoValorPyro.getText());

        JogadorDAO jogadorDao = new JogadorDAO();

        jogadorDao.atualizaPyro(idJogador);
        jogadorDao.atualizaCarteira(valorHeroi, idJogador);

        textoMoeda.setText(Integer.toString(carteira - valorHeroi));

        JOptionPane.showMessageDialog(rootPane, "Heroi PYRO desbloqueado!!");

        validarValores();

        Jogador jogador = jogadorDao.pesquisaJogador(textoUsuario.getText());

        validarHerois(jogador);

        botaoComprarPyro.setEnabled(false);
    }//GEN-LAST:event_botaoComprarPyroActionPerformed

    private void botaoComprarVikingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComprarVikingActionPerformed
        int carteira = Integer.parseInt(textoMoeda.getText());
        int valorHeroi = Integer.parseInt(textoValorViking.getText());

        JogadorDAO jogadorDao = new JogadorDAO();

        jogadorDao.atualizaViking(idJogador);
        jogadorDao.atualizaCarteira(valorHeroi, idJogador);

        textoMoeda.setText(Integer.toString(carteira - valorHeroi));

        JOptionPane.showMessageDialog(rootPane, "Heroi VIKING desbloqueado!!");

        validarValores();

        Jogador jogador = jogadorDao.pesquisaJogador(textoUsuario.getText());

        validarHerois(jogador);

        botaoComprarViking.setEnabled(false);
    }//GEN-LAST:event_botaoComprarVikingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLojaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLojaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLojaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLojaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLojaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAddQtdAgua;
    private javax.swing.JButton botaoAddQtdGarrafa;
    private javax.swing.JButton botaoAddQtdVitamina;
    private javax.swing.JButton botaoComprarAgua;
    private javax.swing.JButton botaoComprarAndroid;
    private javax.swing.JButton botaoComprarCiborg;
    private javax.swing.JButton botaoComprarGarrafa;
    private javax.swing.JButton botaoComprarPyro;
    private javax.swing.JButton botaoComprarViking;
    private javax.swing.JButton botaoComprarVitamina;
    private javax.swing.JButton botaoRemQtdAgua;
    private javax.swing.JButton botaoRemQtdGarrafa;
    private javax.swing.JButton botaoRemQtdVitamina;
    private javax.swing.JButton botaoSair;
    private javax.swing.JTextField campoQtdAgua;
    private javax.swing.JTextField campoQtdGarrafa;
    private javax.swing.JTextField campoQtdVitamina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JPanel painelAguaMineral;
    private javax.swing.JPanel painelAndroid;
    private javax.swing.JPanel painelCiborg;
    private javax.swing.JPanel painelDisposicaoItens;
    private javax.swing.JPanel painelDisposicaoPersonagen;
    private javax.swing.JPanel painelGarrafaCafe;
    private javax.swing.JScrollPane painelItens;
    private javax.swing.JPanel painelLoja;
    private javax.swing.JPanel painelMochila;
    private javax.swing.JScrollPane painelPersonagens;
    private javax.swing.JTabbedPane painelPrincipal;
    private javax.swing.JPanel painelPyro;
    private javax.swing.JPanel painelViking;
    private javax.swing.JPanel painelVitamina;
    public javax.swing.JLabel textoAgua;
    public javax.swing.JLabel textoApelido;
    public javax.swing.JLabel textoGarrafa;
    public javax.swing.JLabel textoMoeda;
    private javax.swing.JLabel textoTotalAgua;
    private javax.swing.JLabel textoTotalGarrafa;
    private javax.swing.JLabel textoTotalVitamina;
    public javax.swing.JLabel textoUsuario;
    private javax.swing.JLabel textoValorAndroid;
    private javax.swing.JLabel textoValorCiborg;
    private javax.swing.JLabel textoValorPyro;
    private javax.swing.JLabel textoValorViking;
    public javax.swing.JLabel textoVitamina;
    // End of variables declaration//GEN-END:variables
}
