/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Toolkit;
import javax.swing.UIManager;

/**
 *
 * @author Luiz
 */
public class TelaPrincipalGUI extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalGUI
     */
    public TelaPrincipalGUI() {
        initComponents();
        
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagemLogo = new javax.swing.JLabel();
        painelBotoes = new javax.swing.JPanel();
        botaoIniciar = new javax.swing.JButton();
        botaoRegras = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BROKEN WORDS BATTLE");
        setResizable(false);

        imagemLogo.setBackground(new java.awt.Color(0, 0, 0));
        imagemLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemLogo.png"))); // NOI18N
        imagemLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        painelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botaoIniciar.setBackground(new java.awt.Color(0, 0, 0));
        botaoIniciar.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        botaoIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemPlay.png"))); // NOI18N
        botaoIniciar.setText("INICIAR");
        botaoIniciar.setFocusPainted(false);
        botaoIniciar.setFocusable(false);
        botaoIniciar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });

        botaoRegras.setBackground(new java.awt.Color(0, 0, 0));
        botaoRegras.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        botaoRegras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemRegras.png"))); // NOI18N
        botaoRegras.setText("REGRAS");
        botaoRegras.setFocusPainted(false);
        botaoRegras.setFocusable(false);
        botaoRegras.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        botaoRegras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegrasActionPerformed(evt);
            }
        });

        botaoSair.setBackground(new java.awt.Color(0, 0, 0));
        botaoSair.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemSairMaior.png"))); // NOI18N
        botaoSair.setText("SAIR");
        botaoSair.setFocusPainted(false);
        botaoSair.setFocusable(false);
        botaoSair.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelBotoesLayout.createSequentialGroup()
                        .addComponent(botaoRegras)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoRegras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagemLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/iconeJogo.png")));
    }

    private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarActionPerformed
        TelaLoginGUI telaLogin = new TelaLoginGUI();

        telaLogin.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_botaoIniciarActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoRegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegrasActionPerformed
        TelaRegrasGUI telaRegras = new TelaRegrasGUI();
        
        telaRegras.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_botaoRegrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JButton botaoRegras;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel imagemLogo;
    private javax.swing.JPanel painelBotoes;
    // End of variables declaration//GEN-END:variables
}
