/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.Login;
import dao.JogadorDAO;
import dao.LoginDAO;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Luiz
 */
public class TelaCadastroGUI extends javax.swing.JFrame {

    private ImageIcon iconeErrado;
    private ImageIcon iconeCerto;

    /**
     * Creates new form TelaCadastroGUI
     */
    public TelaCadastroGUI() {
        initComponents();

        configuraImagens();
        
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        painelJogador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoApelido = new javax.swing.JTextField();
        campoUsuario = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        botaoCadastrar = new javax.swing.JButton();
        alertaApelido = new javax.swing.JLabel();
        alertaUsuario = new javax.swing.JLabel();
        alertaSenha = new javax.swing.JLabel();
        textoErro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BROKEN WORDS BATTLE");
        setResizable(false);

        painelJogador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações para cadastro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemCadUsuario.png"))); // NOI18N
        jLabel1.setLabelFor(campoUsuario);
        jLabel1.setText("Usuário:");

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemCadSenha.png"))); // NOI18N
        jLabel2.setLabelFor(campoSenha);
        jLabel2.setText("Senha:");

        campoApelido.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        campoApelido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoApelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoApelidoKeyTyped(evt);
            }
        });

        campoUsuario.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        campoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoUsuario.setToolTipText("");
        campoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoUsuarioKeyTyped(evt);
            }
        });

        campoSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoSenha.setToolTipText("7 - 14 Caracteres");
        campoSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoSenhaKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemNickname.png"))); // NOI18N
        jLabel4.setLabelFor(campoApelido);
        jLabel4.setText("Apelido:");

        botaoCadastrar.setBackground(new java.awt.Color(0, 204, 0));
        botaoCadastrar.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        botaoCadastrar.setText("CADASTRAR");
        botaoCadastrar.setFocusPainted(false);
        botaoCadastrar.setFocusable(false);
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        alertaApelido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemErrado.png"))); // NOI18N
        alertaApelido.setLabelFor(campoApelido);

        alertaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemErrado.png"))); // NOI18N
        alertaUsuario.setLabelFor(campoUsuario);

        alertaSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemErrado.png"))); // NOI18N
        alertaSenha.setLabelFor(campoSenha);

        textoErro.setFont(new java.awt.Font("Maiandra GD", 1, 10)); // NOI18N
        textoErro.setForeground(new java.awt.Color(240, 240, 240));
        textoErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoErro.setText("Preencha os campos corretamente!!");

        javax.swing.GroupLayout painelJogadorLayout = new javax.swing.GroupLayout(painelJogador);
        painelJogador.setLayout(painelJogadorLayout);
        painelJogadorLayout.setHorizontalGroup(
            painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelJogadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelJogadorLayout.createSequentialGroup()
                        .addGroup(painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelJogadorLayout.createSequentialGroup()
                                .addComponent(campoApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alertaApelido))
                            .addGroup(painelJogadorLayout.createSequentialGroup()
                                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alertaUsuario))
                            .addGroup(painelJogadorLayout.createSequentialGroup()
                                .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alertaSenha)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textoErro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelJogadorLayout.setVerticalGroup(
            painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelJogadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alertaApelido)
                    .addGroup(painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(campoApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alertaUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alertaSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoErro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/iconeJogo.png")));
    }

    private void configuraImagens() {
        iconeErrado = new ImageIcon("src/imagens/imagemErrado.png");
        iconeCerto = new ImageIcon("src/imagens/imagemCerto.png");
    }

    private void campoApelidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoApelidoKeyTyped
        String texto = campoApelido.getText();

        if (texto.isEmpty()) {
            alertaApelido.setIcon(iconeErrado);
        } else {
            alertaApelido.setIcon(iconeCerto);
        }
    }//GEN-LAST:event_campoApelidoKeyTyped

    private void campoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUsuarioKeyTyped
        String texto = campoUsuario.getText();

        if (texto.isEmpty()) {
            alertaUsuario.setIcon(iconeErrado);
        } else {
            alertaUsuario.setIcon(iconeCerto);
        }
    }//GEN-LAST:event_campoUsuarioKeyTyped

    private void campoSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoSenhaKeyTyped
        char[] texto = campoSenha.getPassword();

        if (texto.length >= 6) {
            alertaSenha.setIcon(iconeCerto);
        } else {
            alertaSenha.setIcon(iconeErrado);
        }
    }//GEN-LAST:event_campoSenhaKeyTyped

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        if (alertaApelido.getIcon().equals(iconeCerto) && alertaUsuario.getIcon().equals(iconeCerto) && alertaSenha.getIcon().equals(iconeCerto)) {
            String apelido = campoApelido.getText();
            String usuario = campoUsuario.getText();

            char[] caracteresSenha = campoSenha.getPassword();
            String senha = String.valueOf(caracteresSenha);

            Login login = new Login(apelido, usuario, senha);

            try {
                LoginDAO loginDao = new LoginDAO();
                loginDao.adicionaLogin(login);

                JogadorDAO jogadorDao = new JogadorDAO();
                jogadorDao.adicionaJogador(login.getIdLogin());

                JOptionPane.showMessageDialog(rootPane, login.getApelido() + " cadastrado com sucesso!!");

                TelaLoginGUI telaLogin = new TelaLoginGUI();
                telaLogin.setVisible(true);

                this.dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar!!");
            }
        } else {
            Color color;

            color = new Color(204, 0, 0);

            textoErro.setForeground(color);
        }


    }//GEN-LAST:event_botaoCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertaApelido;
    private javax.swing.JLabel alertaSenha;
    private javax.swing.JLabel alertaUsuario;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JTextField campoApelido;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel painelJogador;
    private javax.swing.JLabel textoErro;
    // End of variables declaration//GEN-END:variables
}
