/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.Controle;
import model.Mestre;
import model.Palavras;
import dao.JogadorDAO;
import dao.MestreDAO;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.LinkedList;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.UIManager;

/**
 *
 * @author Luiz
 */
public class TelaJogoGUI extends javax.swing.JFrame {

    private Timer timer;
    private TimerTask task;
    private Controle controle;
    private Palavras palavras;

    public String usuario;
    public String apelido;
    public String heroiSelecionado;
    public int idJogador;

    private int tempo;

    private LinkedList<Mestre> lista = new <Mestre>LinkedList();

    /**
     * Creates new form TelaJogoGUI
     */
    public TelaJogoGUI() {
        initComponents();

        //Configuração Jogada
        controle = new Controle();
        controle.setPontosGanhos();

        //Configuracao Tempo
        tempoTela();
        iniciarTempo();

        //Configuracao Botoes
        configurarBotoes();

        escolheMestre();

        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMestre = new javax.swing.JPanel();
        imagemMestre = new javax.swing.JLabel();
        barraMestre = new javax.swing.JProgressBar();
        textoMestre = new javax.swing.JLabel();
        painelBotoes = new javax.swing.JPanel();
        botaoPainel1 = new javax.swing.JButton();
        botaoPainel2 = new javax.swing.JButton();
        botaoPainel3 = new javax.swing.JButton();
        botaoPainel5 = new javax.swing.JButton();
        botaoPainel6 = new javax.swing.JButton();
        botaoPainel7 = new javax.swing.JButton();
        botaoPainel4 = new javax.swing.JButton();
        botaoPainel8 = new javax.swing.JButton();
        botaoPainel9 = new javax.swing.JButton();
        botaoPainel10 = new javax.swing.JButton();
        botaoPainel11 = new javax.swing.JButton();
        botaoPainel12 = new javax.swing.JButton();
        botaoPainel13 = new javax.swing.JButton();
        botaoPainel14 = new javax.swing.JButton();
        botaoPainel15 = new javax.swing.JButton();
        botaoPainel16 = new javax.swing.JButton();
        painelJogador = new javax.swing.JPanel();
        textoJogador = new javax.swing.JLabel();
        barraJogador = new javax.swing.JProgressBar();
        botaoHabilidadeHeroi = new javax.swing.JButton();
        painelInformacoes = new javax.swing.JPanel();
        painelItens = new javax.swing.JPanel();
        botaoAgua = new javax.swing.JButton();
        botaoGarrafa = new javax.swing.JButton();
        botaoVitamina = new javax.swing.JButton();
        textoPontuacao = new javax.swing.JLabel();
        campoPontuacao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        barraTempo = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        campoPalavra = new javax.swing.JTextField();
        painelHabilidade = new javax.swing.JPanel();
        barraHabilidade = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BROKEN WORDS BATTLE");
        setResizable(false);

        painelMestre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imagemMestre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagemMestre.setPreferredSize(new java.awt.Dimension(48, 48));

        barraMestre.setBackground(new java.awt.Color(0, 0, 0));
        barraMestre.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        barraMestre.setForeground(new java.awt.Color(102, 153, 0));
        barraMestre.setMaximum(80);
        barraMestre.setValue(80);
        barraMestre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        barraMestre.setFocusable(false);
        barraMestre.setStringPainted(true);

        textoMestre.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoMestre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoMestre.setText("Nivel");
        textoMestre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout painelMestreLayout = new javax.swing.GroupLayout(painelMestre);
        painelMestre.setLayout(painelMestreLayout);
        painelMestreLayout.setHorizontalGroup(
            painelMestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMestreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagemMestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraMestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoMestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelMestreLayout.setVerticalGroup(
            painelMestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMestreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelMestreLayout.createSequentialGroup()
                        .addComponent(textoMestre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barraMestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(imagemMestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelBotoes.setBackground(new java.awt.Color(204, 204, 204));
        painelBotoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        botaoPainel1.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel1.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel1.setFocusPainted(false);
        botaoPainel1.setFocusable(false);
        botaoPainel1.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel1ActionPerformed(evt);
            }
        });

        botaoPainel2.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel2.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel2.setToolTipText("");
        botaoPainel2.setFocusPainted(false);
        botaoPainel2.setFocusable(false);
        botaoPainel2.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel2ActionPerformed(evt);
            }
        });

        botaoPainel3.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel3.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel3.setFocusPainted(false);
        botaoPainel3.setFocusable(false);
        botaoPainel3.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel3ActionPerformed(evt);
            }
        });

        botaoPainel5.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel5.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel5.setFocusPainted(false);
        botaoPainel5.setFocusable(false);
        botaoPainel5.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel5ActionPerformed(evt);
            }
        });

        botaoPainel6.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel6.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel6.setFocusPainted(false);
        botaoPainel6.setFocusable(false);
        botaoPainel6.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel6ActionPerformed(evt);
            }
        });

        botaoPainel7.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel7.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel7.setFocusPainted(false);
        botaoPainel7.setFocusable(false);
        botaoPainel7.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel7ActionPerformed(evt);
            }
        });

        botaoPainel4.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel4.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel4.setToolTipText("");
        botaoPainel4.setFocusPainted(false);
        botaoPainel4.setFocusable(false);
        botaoPainel4.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel4ActionPerformed(evt);
            }
        });

        botaoPainel8.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel8.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel8.setFocusPainted(false);
        botaoPainel8.setFocusable(false);
        botaoPainel8.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel8ActionPerformed(evt);
            }
        });

        botaoPainel9.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel9.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel9.setFocusPainted(false);
        botaoPainel9.setFocusable(false);
        botaoPainel9.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel9ActionPerformed(evt);
            }
        });

        botaoPainel10.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel10.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel10.setFocusPainted(false);
        botaoPainel10.setFocusable(false);
        botaoPainel10.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel10ActionPerformed(evt);
            }
        });

        botaoPainel11.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel11.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel11.setFocusPainted(false);
        botaoPainel11.setFocusable(false);
        botaoPainel11.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel11ActionPerformed(evt);
            }
        });

        botaoPainel12.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel12.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel12.setFocusPainted(false);
        botaoPainel12.setFocusable(false);
        botaoPainel12.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel12ActionPerformed(evt);
            }
        });

        botaoPainel13.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel13.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel13.setFocusPainted(false);
        botaoPainel13.setFocusable(false);
        botaoPainel13.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel13ActionPerformed(evt);
            }
        });

        botaoPainel14.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel14.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel14.setFocusPainted(false);
        botaoPainel14.setFocusable(false);
        botaoPainel14.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel14ActionPerformed(evt);
            }
        });

        botaoPainel15.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel15.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel15.setFocusPainted(false);
        botaoPainel15.setFocusable(false);
        botaoPainel15.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel15ActionPerformed(evt);
            }
        });

        botaoPainel16.setBackground(new java.awt.Color(0, 0, 0));
        botaoPainel16.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        botaoPainel16.setFocusPainted(false);
        botaoPainel16.setFocusable(false);
        botaoPainel16.setPreferredSize(new java.awt.Dimension(70, 70));
        botaoPainel16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainel16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelBotoesLayout.createSequentialGroup()
                        .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoPainel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelBotoesLayout.createSequentialGroup()
                                .addComponent(botaoPainel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoPainel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoPainel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelBotoesLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(botaoPainel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoPainel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoPainel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(painelBotoesLayout.createSequentialGroup()
                        .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botaoPainel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoPainel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoPainel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelBotoesLayout.createSequentialGroup()
                                .addComponent(botaoPainel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(botaoPainel11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                                .addComponent(botaoPainel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoPainel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoPainel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoPainel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPainel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPainel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPainel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPainel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPainel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPainel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPainel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPainel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPainel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPainel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPainel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPainel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPainel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPainel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPainel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPainel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelJogador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textoJogador.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoJogador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoJogador.setText("Apelido");
        textoJogador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        barraJogador.setBackground(new java.awt.Color(0, 0, 0));
        barraJogador.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        barraJogador.setForeground(new java.awt.Color(102, 153, 0));
        barraJogador.setMaximum(50);
        barraJogador.setValue(50);
        barraJogador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        barraJogador.setStringPainted(true);

        botaoHabilidadeHeroi.setBorder(null);
        botaoHabilidadeHeroi.setEnabled(false);
        botaoHabilidadeHeroi.setFocusPainted(false);
        botaoHabilidadeHeroi.setFocusable(false);
        botaoHabilidadeHeroi.setPreferredSize(new java.awt.Dimension(48, 48));
        botaoHabilidadeHeroi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHabilidadeHeroiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelJogadorLayout = new javax.swing.GroupLayout(painelJogador);
        painelJogador.setLayout(painelJogadorLayout);
        painelJogadorLayout.setHorizontalGroup(
            painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelJogadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoHabilidadeHeroi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barraJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelJogadorLayout.setVerticalGroup(
            painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelJogadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelJogadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoHabilidadeHeroi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelJogadorLayout.createSequentialGroup()
                        .addComponent(textoJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barraJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        painelInformacoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        painelItens.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ITENS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 12))); // NOI18N

        botaoAgua.setBackground(new java.awt.Color(0, 204, 204));
        botaoAgua.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        botaoAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemAgua.png"))); // NOI18N
        botaoAgua.setEnabled(false);
        botaoAgua.setFocusPainted(false);
        botaoAgua.setFocusable(false);
        botaoAgua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoAgua.setPreferredSize(new java.awt.Dimension(98, 98));
        botaoAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAguaActionPerformed(evt);
            }
        });

        botaoGarrafa.setBackground(new java.awt.Color(0, 153, 153));
        botaoGarrafa.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        botaoGarrafa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemGarrafa.png"))); // NOI18N
        botaoGarrafa.setEnabled(false);
        botaoGarrafa.setFocusPainted(false);
        botaoGarrafa.setFocusable(false);
        botaoGarrafa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoGarrafa.setPreferredSize(new java.awt.Dimension(98, 98));
        botaoGarrafa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGarrafaActionPerformed(evt);
            }
        });

        botaoVitamina.setBackground(new java.awt.Color(153, 153, 153));
        botaoVitamina.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        botaoVitamina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemVitamina.png"))); // NOI18N
        botaoVitamina.setEnabled(false);
        botaoVitamina.setFocusPainted(false);
        botaoVitamina.setFocusable(false);
        botaoVitamina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoVitamina.setPreferredSize(new java.awt.Dimension(98, 98));
        botaoVitamina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVitaminaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelItensLayout = new javax.swing.GroupLayout(painelItens);
        painelItens.setLayout(painelItensLayout);
        painelItensLayout.setHorizontalGroup(
            painelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelItensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelItensLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoGarrafa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelItensLayout.createSequentialGroup()
                        .addGroup(painelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoVitamina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelItensLayout.setVerticalGroup(
            painelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelItensLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoGarrafa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoVitamina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        textoPontuacao.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        textoPontuacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoPontuacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemPontuacao.png"))); // NOI18N
        textoPontuacao.setText("PONTUAÇÃO");

        campoPontuacao.setEditable(false);
        campoPontuacao.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        campoPontuacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoPontuacao.setText("0");

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemRelogio.png"))); // NOI18N
        jLabel2.setText("TEMPO");

        barraTempo.setBackground(new java.awt.Color(0, 0, 0));
        barraTempo.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        barraTempo.setMaximum(360);
        barraTempo.setValue(360);
        barraTempo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        barraTempo.setFocusable(false);
        barraTempo.setString("00:00");
        barraTempo.setStringPainted(true);

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PALAVRA");

        campoPalavra.setEditable(false);
        campoPalavra.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
        campoPalavra.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout painelInformacoesLayout = new javax.swing.GroupLayout(painelInformacoes);
        painelInformacoes.setLayout(painelInformacoesLayout);
        painelInformacoesLayout.setHorizontalGroup(
            painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoPontuacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barraTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoPalavra)
                    .addComponent(campoPontuacao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelInformacoesLayout.setVerticalGroup(
            painelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoPontuacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelHabilidade.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        barraHabilidade.setForeground(new java.awt.Color(255, 204, 0));
        barraHabilidade.setToolTipText("");
        barraHabilidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        barraHabilidade.setFocusable(false);
        barraHabilidade.setString("");
        barraHabilidade.setStringPainted(true);

        javax.swing.GroupLayout painelHabilidadeLayout = new javax.swing.GroupLayout(painelHabilidade);
        painelHabilidade.setLayout(painelHabilidadeLayout);
        painelHabilidadeLayout.setHorizontalGroup(
            painelHabilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelHabilidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barraHabilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelHabilidadeLayout.setVerticalGroup(
            painelHabilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelHabilidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barraHabilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelJogador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelMestre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelHabilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelInformacoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelMestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelHabilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/iconeJogo.png")));
    }

    private void tempoTela() {
        tempo = controle.getTempoRodada();
        barraTempo.setMaximum(tempo);
        barraTempo.setValue(tempo);

        timer = new Timer();
        task = new TimerTask() {
            @Override
            public void run() {
                tempo--;

                barraTempo.setValue(tempo);

                int minutos = tempo / 60;
                int segundos = tempo % 60;

                if (minutos == 0 && segundos <= 30) {
                    barraTempo.setForeground(Color.RED);
                } else {
                    Color color = new Color(51, 153, 255);
                    barraTempo.setForeground(color);
                }

                if (tempo > 0) {
                    if (segundos < 10) {
                        barraTempo.setString(minutos + ":0" + segundos);
                    } else {
                        barraTempo.setString(minutos + ":" + segundos);
                    }
                } else {
                    finalizaJogo();
                }
            }
        };
    }

    private void iniciarTempo() {
        timer.schedule(task, 0, 1000);
    }

    private void pararTempo() {
        timer.cancel();
    }

    private void configurarBotoes() {
        palavras = new Palavras();

        String[] listaCompleta = palavras.sortearPalavra();

        botaoPainel1.setText(listaCompleta[0]);
        botaoPainel2.setText(listaCompleta[1]);
        botaoPainel3.setText(listaCompleta[2]);
        botaoPainel4.setText(listaCompleta[3]);
        botaoPainel5.setText(listaCompleta[4]);
        botaoPainel6.setText(listaCompleta[5]);
        botaoPainel7.setText(listaCompleta[6]);
        botaoPainel8.setText(listaCompleta[7]);
        botaoPainel9.setText(listaCompleta[8]);
        botaoPainel10.setText(listaCompleta[9]);
        botaoPainel11.setText(listaCompleta[10]);
        botaoPainel12.setText(listaCompleta[11]);
        botaoPainel13.setText(listaCompleta[12]);
        botaoPainel14.setText(listaCompleta[13]);
        botaoPainel15.setText(listaCompleta[14]);
        botaoPainel16.setText(listaCompleta[15]);
    }

    private void reiniciarBotoes() {
        if (controle.arrayBotoesApertados[0] == 1 || controle.arrayBotoesApertados[1] == 1) {
            botaoPainel1.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 2 || controle.arrayBotoesApertados[1] == 2) {
            botaoPainel2.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 3 || controle.arrayBotoesApertados[1] == 3) {
            botaoPainel3.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 4 || controle.arrayBotoesApertados[1] == 4) {
            botaoPainel4.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 5 || controle.arrayBotoesApertados[1] == 5) {
            botaoPainel5.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 6 || controle.arrayBotoesApertados[1] == 6) {
            botaoPainel6.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 7 || controle.arrayBotoesApertados[1] == 7) {
            botaoPainel7.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 8 || controle.arrayBotoesApertados[1] == 8) {
            botaoPainel8.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 9 || controle.arrayBotoesApertados[1] == 9) {
            botaoPainel9.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 10 || controle.arrayBotoesApertados[1] == 10) {
            botaoPainel10.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 11 || controle.arrayBotoesApertados[1] == 11) {
            botaoPainel11.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 12 || controle.arrayBotoesApertados[1] == 12) {
            botaoPainel12.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 13 || controle.arrayBotoesApertados[1] == 13) {
            botaoPainel13.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 14 || controle.arrayBotoesApertados[1] == 14) {
            botaoPainel14.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 15 || controle.arrayBotoesApertados[1] == 15) {
            botaoPainel15.setEnabled(true);
        }

        if (controle.arrayBotoesApertados[0] == 16 || controle.arrayBotoesApertados[1] == 16) {
            botaoPainel16.setEnabled(true);
        }
    }

    private void reiniciarNivel() {
        botaoPainel1.setEnabled(true);
        botaoPainel2.setEnabled(true);
        botaoPainel3.setEnabled(true);
        botaoPainel4.setEnabled(true);
        botaoPainel5.setEnabled(true);
        botaoPainel6.setEnabled(true);
        botaoPainel7.setEnabled(true);
        botaoPainel8.setEnabled(true);
        botaoPainel9.setEnabled(true);
        botaoPainel10.setEnabled(true);
        botaoPainel11.setEnabled(true);
        botaoPainel12.setEnabled(true);
        botaoPainel13.setEnabled(true);
        botaoPainel14.setEnabled(true);
        botaoPainel15.setEnabled(true);
        botaoPainel16.setEnabled(true);

        configurarBotoes();
        escolheMestre();

        barraMestre.setValue(80);
    }

    private void validarJogada() {
        if (controle.verificarJogada() == true) {
            if (palavras.verificarPalavra() == true) {
                campoPalavra.setForeground(new Color(51, 102, 0));

                controle.reiniciaBotao();

                tempo += 6;

                int vidaMestre = barraMestre.getValue();
                vidaMestre -= 10;
                barraMestre.setValue(vidaMestre);

                controle.somaPontuacao();

                campoPontuacao.setText(Integer.toString(controle.getPontuacao()));

                if (!heroiSelecionado.equals("APRENDIZ")) {
                    controle.somaHabilidade();
                    barraHabilidade.setValue(controle.getHabilidade());

                    if (controle.verificaHabilidade() == true) {
                        botaoHabilidadeHeroi.setEnabled(true);
                    }
                }

                if (barraMestre.getValue() == 0) {
                    reiniciarNivel();

                    controle.setMultiplicadorNivel();
                    controle.setPontosGanhos();
                }
            } else {
                campoPalavra.setForeground(new Color(153, 0, 0));

                reiniciarBotoes();

                int vidaJogador = barraJogador.getValue();
                vidaJogador -= 5;
                barraJogador.setValue(vidaJogador);

                if (vidaJogador == 0) {
                    finalizaJogo();
                }

                controle.reiniciaBotao();
            }
        } else {
            campoPalavra.setForeground(new Color(0, 0, 0));
        }
    }

    public void finalizaJogo() {
        pararTempo();

        if (apelido.equals("Convidado")) {
            TelaPrincipalGUI telaPrincipal = new TelaPrincipalGUI();

            telaPrincipal.setVisible(true);

            this.dispose();
        } else {
            TelaFinalizaGUI telaFinaliza = new TelaFinalizaGUI();

            telaFinaliza.usuario = usuario;
            telaFinaliza.apelido = apelido;
            telaFinaliza.idJogador = idJogador;
            telaFinaliza.textoApelido.setText(textoJogador.getText());
            telaFinaliza.imagemJogador.setIcon(botaoHabilidadeHeroi.getIcon());
            telaFinaliza.textoPontuacaoTotal.setText(campoPontuacao.getText());

            telaFinaliza.iniciarTela();

            telaFinaliza.setVisible(true);

            this.dispose();
        }

    }

    public void iniciarMestre() {
        MestreDAO mestreDao = new MestreDAO();

        lista = mestreDao.pesquisaMestre();
    }

    public void escolheMestre() {
        if (!lista.isEmpty()) {
            Random r = new Random();
            int indice = r.nextInt(lista.size());

            Mestre mestre = lista.remove(indice);

            textoMestre.setText(mestre.getNome());
            imagemMestre.setIcon(new javax.swing.ImageIcon(getClass().getResource(mestre.getImagem())));
        } else {
            iniciarMestre();
            escolheMestre();
        }
    }

    private void botaoAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAguaActionPerformed
        int vidaJogador = barraJogador.getValue();

        vidaJogador += 5;

        barraJogador.setValue(vidaJogador);

        botaoAgua.setEnabled(false);

        JogadorDAO jogadorDao = new JogadorDAO();

        jogadorDao.removeAgua(idJogador);
    }//GEN-LAST:event_botaoAguaActionPerformed

    private void botaoGarrafaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGarrafaActionPerformed
        int vidaJogador = barraJogador.getMaximum();

        barraJogador.setValue(vidaJogador);

        botaoGarrafa.setEnabled(false);

        JogadorDAO jogadorDao = new JogadorDAO();

        jogadorDao.removeGarrafa(idJogador);
    }//GEN-LAST:event_botaoGarrafaActionPerformed

    private void botaoVitaminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVitaminaActionPerformed
        controle.multiplicaBonus();
        controle.setPontosGanhos();

        botaoVitamina.setEnabled(false);

        JogadorDAO jogadorDao = new JogadorDAO();

        jogadorDao.removeVitamina(idJogador);
    }//GEN-LAST:event_botaoVitaminaActionPerformed

    private void botaoPainel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel1ActionPerformed
        String palavraBotao = botaoPainel1.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(1);

        botaoPainel1.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel1ActionPerformed

    private void botaoPainel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel2ActionPerformed
        String palavraBotao = botaoPainel2.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(2);

        botaoPainel2.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel2ActionPerformed

    private void botaoPainel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel3ActionPerformed
        String palavraBotao = botaoPainel3.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(3);

        botaoPainel3.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel3ActionPerformed

    private void botaoPainel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel4ActionPerformed
        String palavraBotao = botaoPainel4.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(4);

        botaoPainel4.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel4ActionPerformed

    private void botaoPainel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel5ActionPerformed
        String palavraBotao = botaoPainel5.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(5);

        botaoPainel5.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel5ActionPerformed

    private void botaoPainel6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel6ActionPerformed
        String palavraBotao = botaoPainel6.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(6);

        botaoPainel6.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel6ActionPerformed

    private void botaoPainel7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel7ActionPerformed
        String palavraBotao = botaoPainel7.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(7);

        botaoPainel7.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel7ActionPerformed

    private void botaoPainel8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel8ActionPerformed
        String palavraBotao = botaoPainel8.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(8);

        botaoPainel8.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel8ActionPerformed

    private void botaoPainel9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel9ActionPerformed
        String palavraBotao = botaoPainel9.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(9);

        botaoPainel9.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel9ActionPerformed

    private void botaoPainel10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel10ActionPerformed
        String palavraBotao = botaoPainel10.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(10);

        botaoPainel10.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel10ActionPerformed

    private void botaoPainel11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel11ActionPerformed
        String palavraBotao = botaoPainel11.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(11);

        botaoPainel11.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel11ActionPerformed

    private void botaoPainel12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel12ActionPerformed
        String palavraBotao = botaoPainel12.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(12);

        botaoPainel12.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel12ActionPerformed

    private void botaoPainel13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel13ActionPerformed
        String palavraBotao = botaoPainel13.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(13);

        botaoPainel13.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel13ActionPerformed

    private void botaoPainel14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel14ActionPerformed
        String palavraBotao = botaoPainel14.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(14);

        botaoPainel14.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel14ActionPerformed

    private void botaoPainel15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel15ActionPerformed
        String palavraBotao = botaoPainel15.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(15);

        botaoPainel15.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel15ActionPerformed

    private void botaoPainel16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainel16ActionPerformed
        String palavraBotao = botaoPainel16.getText();

        campoPalavra.setText(palavras.formataPalavra(palavraBotao));

        controle.somaJogada();
        controle.guardarBotao(16);

        botaoPainel16.setEnabled(false);

        validarJogada();
    }//GEN-LAST:event_botaoPainel16ActionPerformed

    private void botaoHabilidadeHeroiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHabilidadeHeroiActionPerformed
        botaoHabilidadeHeroi.setEnabled(false);

        if (heroiSelecionado.equals("CIBORG")) {
            int pontuacaoAtual = Integer.parseInt(campoPontuacao.getText());

            pontuacaoAtual *= 2;

            campoPontuacao.setText(Integer.toString(pontuacaoAtual));
        } else if (heroiSelecionado.equals("ANDROID")) {
            int vidaJogador = barraJogador.getMaximum();

            barraJogador.setValue(vidaJogador);
        } else if (heroiSelecionado.equals("PYRO")) {
            int pontuacaoAtual = Integer.parseInt(campoPontuacao.getText());

            pontuacaoAtual += 3000;

            campoPontuacao.setText(Integer.toString(pontuacaoAtual));

            reiniciarNivel();
        } else if (heroiSelecionado.equals("VIKING")) {
            tempo *= 2;
        }

        controle.reiniciarHabilidade();
        barraHabilidade.setValue(0);
    }//GEN-LAST:event_botaoHabilidadeHeroiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar barraHabilidade;
    private javax.swing.JProgressBar barraJogador;
    private javax.swing.JProgressBar barraMestre;
    private javax.swing.JProgressBar barraTempo;
    public javax.swing.JButton botaoAgua;
    public javax.swing.JButton botaoGarrafa;
    public javax.swing.JButton botaoHabilidadeHeroi;
    private javax.swing.JButton botaoPainel1;
    private javax.swing.JButton botaoPainel10;
    private javax.swing.JButton botaoPainel11;
    private javax.swing.JButton botaoPainel12;
    private javax.swing.JButton botaoPainel13;
    private javax.swing.JButton botaoPainel14;
    private javax.swing.JButton botaoPainel15;
    private javax.swing.JButton botaoPainel16;
    private javax.swing.JButton botaoPainel2;
    private javax.swing.JButton botaoPainel3;
    private javax.swing.JButton botaoPainel4;
    private javax.swing.JButton botaoPainel5;
    private javax.swing.JButton botaoPainel6;
    private javax.swing.JButton botaoPainel7;
    private javax.swing.JButton botaoPainel8;
    private javax.swing.JButton botaoPainel9;
    public javax.swing.JButton botaoVitamina;
    private javax.swing.JTextField campoPalavra;
    private javax.swing.JTextField campoPontuacao;
    private javax.swing.JLabel imagemMestre;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelHabilidade;
    private javax.swing.JPanel painelInformacoes;
    private javax.swing.JPanel painelItens;
    private javax.swing.JPanel painelJogador;
    private javax.swing.JPanel painelMestre;
    public javax.swing.JLabel textoJogador;
    private javax.swing.JLabel textoMestre;
    private javax.swing.JLabel textoPontuacao;
    // End of variables declaration//GEN-END:variables
}
